# Base options and settings
[midi]
path = "./midi/imperial-march.mid"
parallel_mode = "collapse"

# Trumpet
[[tracks]]
track = 1

[[tracks.channels]]
channel = 1
ports = [1]

# Cello
[[tracks]]
track = 2

[[tracks.channels]]
channel = 2
ports = [2]

# Strings
[[tracks]]
track = 3

[[tracks.channels]]
channel = 3
ports = [3]

# Contrabass
[[tracks]]
track = 5

[[tracks.channels]]
channel = 5
ports = [4]
