# Base options and settings
[midi]
path = "./midi/pirates-of-the-caribbean.mid"
parallel_mode = "collapse"

# Right Hand
[[tracks]]
track = 1

[[tracks.channels]]
channel = 1
ports = [2]

# Left Hand
[[tracks]]
track = 2

[[tracks.channels]]
channel = 2
ports = [1]
